### ISSUE TITLE
Track PR #286

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#336]
Following PR #286, file issues with:
- [x]  [Gecko](https://bugzilla.mozilla.org/show_bug.cgi?id=1359269)
- [x]  [WebKit](https://webkit.org/b/170759)
- [x]  [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=714866)
- [x]  [Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11775361/)
- [x] [idlharness.js](https://github.com/w3c/web-platform-tests/pull/5665) (used by testharness.js to run idl tests)
- [x] [widlparser](https://github.com/plinss/widlparser/issues/24) (used by Bikeshed)
- [x] [webidl2.js](https://github.com/w3c/webidl2.js/issues/60) (used by ReSpec, idlharness.js)
- [ ] Related specs:
  - [ ] HTML: https://github.com/whatwg/html/pull/2580
  - [ ] DOM: https://github.com/whatwg/dom/pull/446
  - [ ] Bikeshed error request: https://github.com/tabatkins/bikeshed/issues/1004
  - [ ] ReSpec error request: https://github.com/w3c/respec/issues/1184

**Comment by dontcallmedom** [comment]
I've filed https://github.com/w3c/webidl2.js/issues/60 FWIW

**Comment by samweinig** [comment]
Tracking this with https://webkit.org/b/170759 for WebKit.

**Comment by domenic** [comment]
I filed everything, so closing now :)
