### ISSUE TITLE
Track PR #323

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#372]
Following PR #323, file issues with:

- [x] Rendering engines:
    - [x] Gecko (https://bugzilla.mozilla.org/show_bug.cgi?id=1375829)
    - [x] WebKit (https://bugs.webkit.org/show_bug.cgi?id=173767)
    - [x] Chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=736332)
    - [x] Edge (https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12458893/)
- [x] Testing:
    - [x] web-platform-tests (w3c/web-platform-tests#6246)
    - [x] idlharness.js (w3c/web-platform-tests#6246)
- [x] Parsers:
    - [x] widlparser (plinss/widlparser#25)
    - [x] WebIDL parser (w3c/webidl2.js#73)
- [x] Related specs:
    - [x] [`PushSubscription`](https://w3c.github.io/push-api/#pushsubscription-interface) (custom) in [Push](https://w3c.github.io/push-api/) (w3c/push-api#266)
    - [x] [`MediaDeviceInfo`](https://w3c.github.io/mediacapture-main/getusermedia.html#idl-def-mediadeviceinfo) (own attributes) in [Media Capture and Streams](https://w3c.github.io/mediacapture-main/getusermedia.html) (w3c/mediacapture-main#469)
    - [x] [`Performance`](http://w3c.github.io/hr-time/#the-performance-interface) (own attributes) in [High Resolution Time Level 3](http://w3c.github.io/hr-time/) (w3c/hr-time#49)
    - [x] [`PerformanceEntry`](https://w3c.github.io/performance-timeline/#dom-performanceentry) (own attributes) in [Performance Timeline Level 2](https://w3c.github.io/performance-timeline/) (w3c/performance-timeline#82)
    - [x] [`PerformanceResourceTiming`](https://w3c.github.io/resource-timing/#idl-def-performanceresourcetiming) (own and inherited attributes) in [Resource Timing Level 3](https://w3c.github.io/resource-timing/) (w3c/resource-timing#112)
    - [x] [`PerformanceNavigation`](https://w3c.github.io/navigation-timing/#the-performancenavigation-interface) (own attributes) in [Navigation Timing Level 2](https://w3c.github.io/navigation-timing/) (w3c/navigation-timing#72)
    - [x] [`PerformanceTiming`](https://w3c.github.io/navigation-timing/#the-performancetiming-interface) (own attributes) in [Navigation Timing Level 2](https://w3c.github.io/navigation-timing/) (w3c/navigation-timing#72)
    - [x] [`PerformanceNavigationTiming`](https://w3c.github.io/navigation-timing/#dom-performancenavigationtiming) (own and inherited attributes) in [Navigation Timing Level 2](https://w3c.github.io/navigation-timing/) (w3c/navigation-timing#72)
    - [x] [`RTCSessionDescription`](http://w3c.github.io/webrtc-pc/#idl-def-rtcsessiondescription) (own attributes) in [WebRTC 1.0: Real-time Communication Between Browsers](http://w3c.github.io/webrtc-pc/) (w3c/webrtc-pc#1419)
    - [x] [`RTCIceCandidate`](http://w3c.github.io/webrtc-pc/#idl-def-rtcicecandidate) (custom) in [WebRTC 1.0: Real-time Communication Between Browsers](http://w3c.github.io/webrtc-pc/) (w3c/webrtc-pc#1419)
    - [x] [`PaymentAddress`](https://w3c.github.io/browser-payment-api/#paymentaddress-interface) (own attributes) in [Payment Request API](https://w3c.github.io/browser-payment-api/) (w3c/browser-payment-api#555)
    - [x] [`PaymentResponse `](https://w3c.github.io/browser-payment-api/#paymentresponse-interface) (own attributes) in [Payment Request API](https://w3c.github.io/browser-payment-api/) (w3c/browser-payment-api#555)
    - [x] [`DOMPointReadOnly`](https://drafts.fxtf.org/geometry/#dompointreadonly) (own attributes) in [Geometry Interfaces Module](https://drafts.fxtf.org/geometry/) (w3c/fxtf-drafts#200)
    - [x] [`DOMRectReadOnly`](https://drafts.fxtf.org/geometry/#domrectreadonly) (own attributes) in [Geometry Interfaces Module](https://drafts.fxtf.org/geometry/) (w3c/fxtf-drafts#200)
    - [x] [`DOMQuad`](https://drafts.fxtf.org/geometry/#domquad) (own attributes) in [Geometry Interfaces Module](https://drafts.fxtf.org/geometry/) (w3c/fxtf-drafts#200)
    - [x] [`DOMMatrixReadOnly`](https://drafts.fxtf.org/geometry/#dommatrixreadonly) (own attributes) in [Geometry Interfaces Module](https://drafts.fxtf.org/geometry/) (w3c/fxtf-drafts#200)
    Additionally, tracking https://github.com/w3c/fxtf-drafts/issues/199.

**Comment by tobie** [comment]
All issues filed; closing.

**Comment by domenic** [comment]
What about the parsers? They should start rejecting serializer syntax, and accepting toJSON if they don't already.

**Comment by tobie** [comment]
So the parsers already accept toJSON as it's just a regular operation (usage wasn't blocked at the grammar level). But you're right that they can get rid of lots of code now that serializers are removed. I hadn't thought about that. :)

**Comment by tobie** [comment]
Also filed bugs with vendors and test suites. Think I'm done this time.
