### ISSUE TITLE
Track PR #364

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#376]
Following PR #364, file issues with:

- [x] Rendering engines:
    - [x] Gecko (https://bugzilla.mozilla.org/show_bug.cgi?id=1366734)
    - [x] WebKit (https://bugs.webkit.org/show_bug.cgi?id=172451)
    - [x] Chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=724252)
    - [x] Edge (https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12091311/)
- [x] Testing:
    - [x] web-platform-tests (w3c/web-platform-tests#5991, w3c/web-platform-tests#6020)
    - [x] idlharness.js (w3c/web-platform-tests#5966)
- [x] Specs:
    - [x] [`HTMLDocument`](https://html.spec.whatwg.org/#htmldocument) in HTML (whatwg/dom#221)
    - [x] [`SVGMatrix` and `WebKitCSSMatrix`](https://drafts.fxtf.org/geometry/#webkitcssmatrix) in CSS Geometry (w3c/fxtf-drafts#167)
    - [x] [`webkitURL`](https://url.spec.whatwg.org/#webkiturl) in URL (whatwg/url#312)
