### ISSUE TITLE
Track PR #425

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#429]
Following PR #425, file issues with:
- [x] Rendering engines:
    - [x] [Gecko](https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=DOM&cc=bzbarsky@mit.edu)
    - [x] [WebKit](https://bugs.webkit.org/enter_bug.cgi?product=WebKit&component=Bindings&short_desc=[WebIDL]%20)
    - [x] [Chromium](https://bugs.chromium.org/p/chromium/issues/entry?template=Defect%20report%20from%20developer&components=Blink%3EBindings&summary=[WebIDL]%20&comment&labels=Via-WebIDLRepo)
    - [x] [Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/)
- [x] Testing: 
    - [ ] [web-platform-tests](https://github.com/w3c/web-platform-tests/issues/new)
    - [x] [idlharness.js](https://github.com/w3c/testharness.js/issues/new?title=%5Bidlharness%5D%20) (used by testharness.js to run idl tests)

There are no syntax changes, so no need to file bugs against parsers.

**Comment by littledan** [comment]
Unless we have a usage outside of WebAssembly and JS, I don't know if any implementation needs to be done in typical WebIDL bindings generators.

**Comment by Ms2ger** [comment]
Testing was done in https://github.com/web-platform-tests/wpt/pull/13032, I think.
