### ISSUE TITLE
Track PR #412

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#434]
Following PR #412, file issues with:

- [x] Rendering engines: https://github.com/whatwg/html/pull/2932#issuecomment-328218246
- [x] Testing:
    - [x] web-platform-tests: w3c/web-platform-tests#7254
    - [x] idlharness.js: w3c/web-platform-tests#7258
- [x] Parsers:
    - [x] widlparser: plinss/widlparser#28   
    - [x] WebIDL parser: w3c/webidl2.js#78

**Comment by TimothyGu** [comment]
Browser issues should reference https://github.com/w3c/web-platform-tests/pull/7254.

web-platform-tests: https://github.com/w3c/web-platform-tests/pull/7254

idlharness.js: https://github.com/w3c/web-platform-tests/issues/7258

widlparser: https://github.com/plinss/widlparser/issues/28

webidl2.js: https://github.com/w3c/webidl2.js/issues/78

**Comment by domenic** [comment]
All checkboxes checked! So let's close. Of course we still want to land #412!
