### ISSUE TITLE
Track PR #433

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#472]
This tracks PR #433.

### Rendering engines ###

File issues with:

- [x] Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1414372
- [x] WebKit: https://bugs.webkit.org/show_bug.cgi?id=179249
- [x] Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=781257
- [x] Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14515931/

### Testing ###

* web-platform-tests: w3c/web-platform-tests#8053
* idlharness.js: w3c/web-platform-tests#8054

### Parsers ###

* widlparser: plinss/widlparser#32
* WebIDL2: w3c/webidl2.js#112

### Spec editors ###

* Bikeshed: tabatkins/bikeshed#1124
* ReSpec: w3c/respec#1423

**Comment by tobie** [comment]
_The body of this comment will be updated shortly. Pease don't edit it as your edits will be lost._

**Comment by domenic** [comment]
Mixins were a great success everyone! Closing!
